{
 "title": "Hermes Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "App Versions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([\n    {\"$group\" : {\"_id\": \"$appVersion\", \"name\": {\"$first\" : \"$appVersion\"}, \"ts\": { \"$first\": \"$createdAt\" }, \"value\":{\"$sum\":1}}},\n    {\"$sort\" : {\"name\" : -1}},{\"$match\" : {\"value\" : {\"$gt\" : 5}}}\n\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Dictionary Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([{\"$match\": { \"metadata.preferences.isUDPluginEnabled\" : true }}, {\"$group\" : {\"_id\" : null , \"value\" : { \"$sum\" : 1}}}, \n{\"$project\" : {\"ts\" : \"$$NOW\", \"name\" : \"Urban Dictionary\", \"value\" : 1}}])",
     "type": "timeserie"
    },
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([{\"$match\": { \"metadata.preferences.en_US\" : true }}, {\"$group\" : {\"_id\" : null , \"value\" : { \"$sum\" : 1}}}, \n{\"$project\" : {\"ts\" : \"$$NOW\", \"name\" : \"Livio English\", \"value\" : 1}}])",
     "type": "timeserie"
    },
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([{\"$match\": { \"metadata.preferences.it_IT\" : true }}, {\"$group\" : {\"_id\" : null , \"value\" : { \"$sum\" : 1}}}, \n{\"$project\" : {\"ts\" : \"$$NOW\", \"name\" : \"Livio Italian\", \"value\" : 1}}])",
     "type": "timeserie"
    },
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([{\"$match\": { \"metadata.preferences.pt_BR\" : true }}, {\"$group\" : {\"_id\" : null , \"value\" : { \"$sum\" : 1}}}, \n{\"$project\" : {\"ts\" : \"$$NOW\", \"name\" : \"Livio Portuguese\", \"value\" : 1}}])",
     "type": "timeserie"
    },
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([{\"$match\": { \"metadata.preferences.de_DE\" : true }}, {\"$group\" : {\"_id\" : null , \"value\" : { \"$sum\" : 1}}}, \n{\"$project\" : {\"ts\" : \"$$NOW\", \"name\" : \"Livio German\", \"value\" : 1}}])",
     "type": "timeserie"
    },
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([{\"$match\": { \"metadata.preferences.fr_FR\" : true }}, {\"$group\" : {\"_id\" : null , \"value\" : { \"$sum\" : 1}}}, \n{\"$project\" : {\"ts\" : \"$$NOW\", \"name\" : \"Livio French\", \"value\" : 1}}])",
     "type": "timeserie"
    },
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([{\"$match\": { \"metadata.preferences.es_ES\" : true }}, {\"$group\" : {\"_id\" : null , \"value\" : { \"$sum\" : 1}}}, \n{\"$project\" : {\"ts\" : \"$$NOW\", \"name\" : \"Livio Spanish\", \"value\" : 1}}])",
     "type": "timeserie"
    },
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([{\"$match\": { \"metadata.preferences.wordnet\" : true }}, {\"$group\" : {\"_id\" : null , \"value\" : { \"$sum\" : 1}}}, \n{\"$project\" : {\"ts\" : \"$$NOW\", \"name\" : \"WordNet\", \"value\" : 1}}])",
     "type": "timeserie"
    },
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([{\"$match\": { \"metadata.preferences.browerTab\" : true }}, {\"$group\" : {\"_id\" : null , \"value\" : { \"$sum\" : 1}}}, \n{\"$project\" : {\"ts\" : \"$$NOW\", \"name\" : \"Google Define\", \"value\" : 1}}])",
     "type": "timeserie"
    },
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([{\"$match\": { \"metadata.preferences.wikipedia\" : true }}, {\"$group\" : {\"_id\" : null , \"value\" : { \"$sum\" : 1}}}, \n{\"$project\" : {\"ts\" : \"$$NOW\", \"name\" : \"Wikipedia\", \"value\" : 1}}])",
     "type": "timeserie"
    },
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([{\"$match\": { \"metadata.preferences.vocabulary\" : true }}, {\"$group\" : {\"_id\" : null , \"value\" : { \"$sum\" : 1}}}, \n{\"$project\" : {\"ts\" : \"$$NOW\", \"name\" : \"Vocabulary.com\", \"value\" : 1}}])",
     "type": "timeserie"
    },
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([{\"$match\": { \"metadata.preferences.cambridge\" : true }}, {\"$group\" : {\"_id\" : null , \"value\" : { \"$sum\" : 1}}}, \n{\"$project\" : {\"ts\" : \"$$NOW\", \"name\" : \"Cambridge\", \"value\" : 1}}])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "OS versions",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([\n    {\"$group\" : {\"_id\": \"$osVersion\", \"name\": {\"$first\" : \"$osVersion\"}, \"ts\": { \"$first\": \"$createdAt\" }, \"value\":{\"$sum\":1}}},\n    {\"$sort\" : {\"name\" : -1}}\n\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Pro Install Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([{\"$match\" : {\"metadata.isProApp\" : true}}, {\"$group\" : {\"_id\" : null , \"value\" : { \"$sum\" : 1}}}, \n{\"$project\" : {\"ts\" : \"$$NOW\", \"name\" : \"Pro Installs\", \"value\" : 1}}])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Total Install Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([ {\"$group\" : {\"_id\" : null , \"value\" : { \"$sum\" : 1}}}, \n{\"$project\" : {\"ts\" : \"$$NOW\", \"name\" : \"Pro Installs\", \"value\" : 1}}])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Build Types",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([\n    {\"$group\" : {\"_id\":{ \"$ifNull\" : [\"$metadata.buildType\", \"Unknown\"]}, \"name\": {\"$first\" : { \"$ifNull\" : [\"$metadata.buildType\", \"Unknown\"]}}, \"ts\": { \"$first\": \"$createdAt\" }, \"value\":{\"$sum\":1}}},\n    {\"$sort\" : {\"name\" : -1}}\n\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Top 10 Today's Word",
   "type": "digrich-bubblechart-panel",
   "gridPos": { "h": 16, "w": 13, "x": 0, "y": 22 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([\n{\"$match\" : {\"metadata.preferences.todaysWord\" : {\"$exists\": true, \"$ne\" : null}}},\n{\"$group\" : {\"_id\" : \"$metadata.preferences.todaysWord\", \"value\":{\"$sum\":1}}},\n{\"$project\" : {\"name\" : \"$_id\", \"ts\" : \"$$NOW\", \"value\" : 1}},\n{\"$sort\" : {\"value\" : -1}},\n{\"$limit\" : 10}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Theme Distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([\n    {\"$group\" : {\"_id\":{ \"$ifNull\" : [\"$metadata.preferences.Theme\", \"LIGHT\"]}, \"name\": {\"$first\" : { \"$ifNull\" : [\"$metadata.preferences.Theme\", \"LIGHT\"]}}, \"ts\": { \"$first\": \"$createdAt\" }, \"value\":{\"$sum\":1}}},\n{\"$sort\" : {\"name\" : 1}}\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Top 10 Devices",
   "type": "digrich-bubblechart-panel",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 29 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "db.CLOUD_MESSAGING_REGISTRY.aggregate([\n{\"$match\" : {\"deviceName\" : {\"$exists\": true, \"$ne\" : null}}},\n{\"$group\" : {\"_id\" : \"$deviceName\", \"value\":{\"$sum\":1}}},\n{\"$project\" : {\"name\" : \"$_id\", \"ts\" : \"$$NOW\", \"value\" : 1}},\n{\"$sort\" : {\"value\" : -1}},\n{\"$limit\" : 10}\n])",
     "type": "timeserie"
    }
   ]
  }
 ]
}